language: go
go:
- 1.8.x
script:
- make test
before_deploy:
- make release
- export RELEASE_VERSION=$(git describe --tags --always)
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file:
    - "agentmon-${RELEASE_VERSION}-linux-amd64.tar.gz"
  on:
    tags: true
  api_key:
    secure: H2iJki39JLbG0b6N8rHuVudqLJgEQyPK8P0X2CHguWA1pWwbXetyIijp8N1nDgPuvZfrkPr0eHg93FmGt0Y5VGghto588EIZ7mhFyAX5RtT/341iwxBdilI45BdkmzDo1YNmOQQUfDIIQG76umwGe+o+raQ/bK7DipRvQbrKUPt1hMLtnRp4yKkG2//UjOwGDJRhzTSOSifOnXwdIGiJUMlYsF2FqsZlOk7zHdvuGVgA2nMrEn9FK8llHwYFWszM+aE9LUwZ7O/1gk0ol6fnODTVUiDifRNATfCNx+z7JJmFsp3xmge8/FrowV9OGdGbkKojHnD3R9ivBjmH+1U7Tg+OFLvymJuftkNKutreHbnZrdyO+RRR0eS7Jl5KCIZxeHfPSVtvZ8hitCcda5Uh32UQU9LegDY3s2ElfhuutO5YquKgjqH2sTlzP1ecBGuqlM49H+q5COz6ITC83wGRvUyRiZ3EJHSYRPgUc+eC6TfLJZs/UsGLtV97ZyD2CMNYHZYufz8erBpp9jCg6jk+nBMf87MNEVEDiqf2Q8bbLcPb1dLTWrLBOGYklj9ifRgacm0//E2CGqUQCMWhlGJqy0iw4Uba5drdLz9YZ6dBZ/qYriRS8diQrLx8V0wGKzlxdpb+avZoXyd5QNso0Ea8ux/963oAwhcygl9sSC/+4Y8=
